# -----------------------------------------------------------------------------------------------------------------------
# viz_SpectrogramRegions.py
# To visualize ROI regions used to generate regional spectrograms.
#
# __author__: Rojin Anbarafshan <rojin.anbar@gmail.com>
# __date__:   2026-04
#
# PURPOSE:
#   - This script is part of the BSL post-processing pipeline.
#   - Reads the CFD HDF5 mesh and the spectrogram-regions CSV, assigns each surface mesh
#     point to an anatomical ROI, and renders a color-coded PNG image.
#   - Each region is colored by the REGION_COLORS dict defined in this script.
#
# REQUIREMENTS:
#   - pyvista, numpy
#   - On Trillium: virtual environment called "pyvista36"
#       > module load StdEnv/2023 gcc/12.3 python/3.12.4
#       > source $HOME/virtual_envs/pyvista36/bin/activate
#       > module load vtk/9.3.0
#
# EXAMPLE CLI (required arguments):
#       > python viz_SpectrogramRegions.py \
#           --mesh_stl       cases/PTSeg028_base_0p64/step0_PreProcess/mesh/PTSeg028_base_0p64.stl \
#           --centerline_csv cases/PTSeg028_base_0p64/step1_CFD/data/PTSeg028_base_0p64_centerline_points_clip_v7.csv \
#           --regions_csv    cases/PTSeg028_base_0p64/step2_PostProcess/PTSeg028_base_0p64_spectrogram_regions.csv \
#           --output_png     cases/PTSeg028_base_0p64/step2_PostProcess/PTSeg028_base_0p64_ROI_regions.png
#
# INPUTS:
#   --mesh_stl       STL file of surface mesh
#   --centerline_csv Centerline CSV   (columns: Points:0/1/2, FrenetTangent:0/1/2)
#   --regions_csv    Regions   CSV    (columns: ROI_start_center_id, ROI_end_center_id,
#                                               region_name [optional], region_abbrev [optional])
#   --output_png     Output PNG path  (default: <regions_csv_dir>/<case>_ROI_regions.png)
#
# OPTIONAL:
#   --bg_color      Background color string           (default: white)
#   --mesh_opacity  Opacity of non-ROI mesh           (default: 0.12)
#   --mesh_color    Color string for non-ROI mesh     (default: lightgrey)
#   --window_size   Image width height in pixels      (default: 1800 2000)
#
# HOW REGION EXTRACTION WORKS:
#   Spectrograms were generated by cutting the surface with thin disks centered at each
#   centerline point from ROI_start_center_id to ROI_end_center_id and collecting the
#   unique wall points intercepted by those disks.
#
#   This is reproduced here by assigning each surface point to its nearest centerline
#   point (Euclidean distance).  A surface point belongs to a region if its assigned
#   centerline index falls within [ROI_start_center_id, ROI_end_center_id] (inclusive).
#   Points and their cells are extracted with pyvista extract_points().
#
# OUTPUTS:
#   PNG image of the colored mesh saved at --output_png.
#
# Copyright (C) 2026 University of Toronto, Biomedical Simulation Lab.
# -----------------------------------------------------------------------------------------------------------------------

import argparse
from pathlib import Path

import h5py
import numpy as np
import pyvista as pv


# ======================================================================================================
# REGION COLOR DEFINITIONS
# ======================================================================================================
# Edit RGB tuples (values in [0.0, 1.0]) to change colors for each region.
# Keys must match 'region_name' values in the regions CSV (case-sensitive).


REGION_COLORS = {
    "1_SSS":      (26,152,80),      
    "2_TS":       (166,217,106),    
    "3_TSS":      (255,210,0),      
    "4_PSR":      (214,96,77),    
    "5_SS":       (37,52,148),     
    "6_JB":       (150,210,210),    
}


# ======================================================================================================
# STEP 1 – LOADING INPUT FILES
# ======================================================================================================

def load_surface_mesh(mesh_file:Path) -> pv.PolyData:
    """
    Build a Pyvista PolyData surface from the wall mesh stored in a BSLSolver-style HDF5 file.

    Expects HDF5 layout:
      Mesh/Wall/coordinates : (Npoints, 3) float    – XYZ node positions
      Mesh/Wall/topology    : (Ncells, 3 or 4) int  – triangle connectivity
      Mesh/Wall/pointIds    : (Npoints,) int        – global volume-mesh point IDs
    """

    with h5py.File(mesh_file, 'r') as h5:
        coords = np.array(h5['Mesh/Wall/coordinates'])      # coords of wall points (n_points, 3)
        cells  = np.array(h5['Mesh/Wall/topology'])         # connectivity of wall points (n_cells, 3) -> triangles
        point_ids   = np.array(h5['Mesh/Wall/pointIds'])    # mapping to volume point IDs (n_points,)
        
    # Create connectivity array compatible with VTK --> requires a size prefix per cell (here '3' for triangles)
    n_cells        = cells.shape[0]
    node_per_cell  = 3                                                      # the surface cells are triangles with size of 3 (3 nodes per elem)
    cell_size      = np.full((n_cells, 1), node_per_cell, dtype=np.int64)   # array of size (n_cells, 1) filled with 3 
    cells_vtk      = np.hstack([cell_size, cells]).ravel()                  # horizontal stacking of arrays / ravel: flattens the array into a 1d array
        
    # Build surface and attach point ID
    surf = pv.PolyData(coords, cells_vtk)
    surf.point_data['vtkOriginalPtIds'] = point_ids

    return surf



def load_centerline_csv(csv_path: Path):
    """
    Read all centerline points and store XYZ positions and Frenet tangents.

    Column names after numpy strips surrounding quotes:
      Points0, Points1, Points2
      FrenetTangent0, FrenetTangent1, FrenetTangent2

    Returns
    -------
    coords  : (N_cl, 3)  XYZ positions along the centerline
    normals : (N_cl, 3)  unit tangent vectors (= cut-plane normals)
    """
    data    = np.genfromtxt(csv_path, delimiter=",", names=True, dtype=float)
    coords  = np.column_stack([data["Points0"],         data["Points1"],        data["Points2"]])
    normals = np.column_stack([data["FrenetTangent0"],  data["FrenetTangent1"], data["FrenetTangent2"]])

    return coords, normals


def load_regions_csv(csv_path: Path) -> list:
    """
    Read ROI region definitions from the spectrogram regions CSV.

    Required columns : ROI_start_center_id, ROI_end_center_id
    Optional columns : region_name, region_abbrev

    Returns a list of dicts, one per region row.
    """
    data = np.genfromtxt(csv_path, delimiter=",", names=True, dtype=None, encoding="utf-8")

    int_cols   = {"ROI_start_center_id", "ROI_end_center_id"}
    str_cols   = {"region_fullname", "region_shortname"}

    regions = []
    for row in data:
        rec = {}
        for key in data.dtype.names:
            val = row[key]
            if key in int_cols:
                rec[key] = int(val)
            elif key in str_cols:
                rec[key] = str(val).strip()
        regions.append(rec)
    return regions


# HELPER – pick color for a region
def get_region_color(roi_params: dict) -> tuple:
    """
    Return the RGB color tuple for a region.
    Looks up REGION_COLORS by region_shortname.
    Falls back to mid-grey if the key is not found in REGION_COLORS.
    """
    name = roi_params.get("region_shortname", "")
    return REGION_COLORS.get(name, (0.5, 0.5, 0.5))
  


# ======================================================================================================
# STEP 4 – CLIP EACH REGION FROM THE SURFACE MESH
# ======================================================================================================

def _nearest_centerline_indices(pts: np.ndarray, centerline_coords: np.ndarray) -> np.ndarray:
    """
    For each point in pts (N, 3) return the index of the nearest centerline point.
    Processed in chunks to avoid large intermediate arrays.
    """
    nearest = np.empty(len(pts), dtype=np.intp)
    chunk = 10_000
    for s in range(0, len(pts), chunk):
        block    = pts[s:s + chunk]
        # compute distance surf points from centerline points
        diffs    = block[:, None, :] - centerline_coords[None, :, :]   # (chunk, N_cl, 3)
        nearest[s:s + chunk] = (diffs ** 2).sum(axis=2).argmin(axis=1)
    return nearest


def clip_region_of_mesh(surf: pv.PolyData,
                        region_params: dict,
                        centerline_coords: np.ndarray,
                        centerline_normals: np.ndarray) -> pv.PolyData:
    """
    Extract the vessel segment for one region.

    Step A – two sequential plane clips (start / end planes) produce clean
             cross-section edges at the region boundaries.
    Step B – nearest-centerline-index mask removes any points that leaked through
             the infinite planes into geometrically adjacent curved regions.

    PyVista clip() convention (wraps VTK vtkClipPolyData):
      invert=False  keeps the half where  normal · (P - origin) <= 0
      invert=True   keeps the half where  normal · (P - origin) >= 0
    """
    start = region_params["ROI_start_center_id"]
    end   = region_params["ROI_end_center_id"]

    # Step A: two plane clips
    clipped = surf.clip(normal=centerline_normals[start], origin=centerline_coords[start], invert=False)
    clipped = clipped.clip(normal=centerline_normals[end], origin=centerline_coords[end], invert=True)

    if clipped.n_points == 0:
        return clipped

    # Step B: drop points whose nearest centerline index falls outside [start, end]
    nearest = _nearest_centerline_indices(np.asarray(clipped.points), centerline_coords)
    mask    = (nearest >= start) & (nearest <= end)
    if not mask.any():
        return pv.PolyData()
    return clipped.extract_points(mask, include_cells=True)


def clip_all_regions(surf: pv.PolyData,
                     region_params: list,
                     centerline_coords: np.ndarray,
                     centerline_normals: np.ndarray) -> list:
    """
    Clip each region and return a list of (region_dict, clipped_PolyData) tuples.
    """
    clipped_regions = []
    for roi_params in region_params:
        clipped_roi = clip_region_of_mesh(surf, roi_params, centerline_coords, centerline_normals)
        clipped_regions.append((roi_params, clipped_roi))
    return clipped_regions



# ======================================================================================================
# STEP 5 – RENDER AND SAVE PNG
# ======================================================================================================

def render_and_save(surf: pv.PolyData,
                    clipped_regions: list,
                    output_png: Path,
                    bg_color: str,
                    mesh_opacity: float,
                    mesh_color: str,
                    window_size: tuple):
    """
    Render the mesh with colored ROI regions and save as PNG.

    Strategy:
      1. Full mesh  – semi-transparent, neutral color  (anatomical context background)
      2. Each clipped ROI mesh – solid, region-specific color layered on top
    """

    plotter = pv.Plotter(off_screen=True, window_size=list(window_size))
    plotter.set_background(bg_color)

    # ---- Full mesh as semi-transparent background --------------------------------------
    plotter.add_mesh(surf, color=mesh_color, opacity=mesh_opacity,
                     smooth_shading=True, show_scalar_bar=False,
                     specular=0.8, specular_power=25)
    
    plotter.add_silhouette(surf, color="silver", line_width=1) # add outline to surface

    # ---- Colored clipped ROI actors ----------------------------------------------------

    for (roi_params, roi_surf) in clipped_regions:
        color = get_region_color(roi_params)

        if roi_surf is not None and roi_surf.n_points > 0:

            # Set region-specific properties
            if roi_params["region_shortname"] == "3_TSS":
                ambient_val = 0.1
                specular_val = 0.5
                specular_power_val = 80
            else:
                ambient_val = 0.3
                specular_val = 0.8
                specular_power_val = 25
            
            plotter.add_mesh(roi_surf, color=color, opacity=0.85,
                             smooth_shading=True, show_scalar_bar=False,
                             specular=specular_val, specular_power=specular_power_val, ambient=ambient_val)



    # ---- Camera ------------------------------------------------------------------------
    plotter.camera.parallel_projection = True                   # CameraParallelProjection = 1
    plotter.camera.parallel_scale      = 101                    # CameraParallelScale
    plotter.camera.position            = (-285, -33.8, 102)     # CameraPosition
    plotter.camera.focal_point         = (20.6, -35.1, -2.8)    # CameraFocalPoint
    plotter.camera.up                  = (0.32, 0.04, 0.94)     # CameraViewUp
  
    # ---- Lighting (soft diffuse, good for medical meshes) ------------------------------
    plotter.enable_lightkit()

    # ---- Save --------------------------------------------------------------------------
    output_png.parent.mkdir(parents=True, exist_ok=True)
    plotter.image_scale = 2   # render at 2x window_size resolution
    plotter.screenshot(str(output_png), transparent_background=False)
    plotter.close()


# ======================================================================================================
# CLI
# ======================================================================================================

def parse_args():
    p = argparse.ArgumentParser(description="Render anatomical ROI regions on the CFD surface mesh and save a PNG.")

    # Define paths
    p.add_argument("--path_mesh_stl",       required=True,  type=Path,  help="Path to surface mesh STL file.")
    p.add_argument("--path_centerline_csv", required=True,  type=Path,  help="Centerline CSV with Points:0/1/2 and FrenetTangent:0/1/2 columns.")
    p.add_argument("--path_regions_csv",    required=True,  type=Path,  help="Spectrogram regions CSV with ROI_start/end_center_id columns.")
    p.add_argument("--path_output_png",     required=True,  type=Path,  help="Output PNG path (default: <regions_csv_dir>/<case>_ROI_regions.png).")

    # Rendering properties
    p.add_argument("--bg_color",     default="white",       type=str,   help="Background color (default: white).")
    p.add_argument("--mesh_opacity", default=0.1,           type=float, help="Opacity of the non-ROI mesh (default: 0.1).")
    p.add_argument("--mesh_color",   default="lightgrey",   type=str,   help="Color of the non-ROI mesh (default: lightgrey).")

    # Camera params
    p.add_argument("--window_size",  default=[1800, 2000],  type=int,   nargs=2, metavar=("WIDTH", "HEIGHT"), help="Output image size in pixels (default: 1800 2000).")

    return p.parse_args()


# ======================================================================================================
# MAIN
# ======================================================================================================

def main():
    args = parse_args()


    print("\n" + "=" * 200)
    print("  viz_SpectrogramRegions.py")
    print("=" * 200)
    print(f"  [info] Mesh STL file  : {args.path_mesh_stl}")
    print(f"  [info] Centerline CSV : {args.path_centerline_csv}")
    print(f"  [info] Regions CSV    : {args.path_regions_csv}")
    print(f"  [info] Output PNG     : {args.path_output_png}")
    print("=" * 200 + "\n")

    # Step 1 – Mesh
    print("[1/5] Loading surface mesh from STL file ...")
    surf = load_surface_mesh(args.path_mesh_stl)
    #surf = pv.read(args.path_mesh_stl)
    print(f"      {surf.n_points} points, {surf.n_cells} cells\n")

    # Step 2 – Centerline
    print("[2/5] Loading centerline from CSV file ...")
    centerline_coords, centerline_normals = load_centerline_csv(args.path_centerline_csv)

    # Step 3 – Regions
    print("[3/5] Loading regions from CSV file ...")
    region_params = load_regions_csv(args.path_regions_csv)

    # Step 4 – Clip each region
    print("[4/5] Clipping all regions from surface mesh ...")
    clipped_regions = clip_all_regions(surf, region_params, centerline_coords, centerline_normals)


    # Step 5 – Render
    print("[5/5] Rendering and saving PNG ...")
    render_and_save(surf,
                    clipped_regions,
                    output_png   = args.path_output_png,
                    bg_color     = args.bg_color,
                    mesh_opacity = args.mesh_opacity,
                    mesh_color   = args.mesh_color,
                    window_size  = tuple(args.window_size))

    print("\nDone.\n")


if __name__ == "__main__":
    main()
